[mypy]
files = dashboard.py, src, tests
python_version = 3.12

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-pyarrow.*]
ignore_missing_imports = True

[mypy-pyqtgraph.*]
ignore_missing_imports = True
